apiVersion: apps/v1
kind: Deployment
metadata:
  name: community-service-deployment
  labels:
    app: community-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: community-service
  template:
    metadata:
      labels:
        app: community-service
    spec:
      containers:
        - name: community-service-container
          imagePullPolicy: Never
          image: "community-microservice:latest"
          ports:
            - containerPort: 8089
          env:
            - name: MODE
              valueFrom:
                secretKeyRef:
                  name: community-service-secret
                  key: MODE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: community-service-secret
                  key: JWT_SECRET
            - name: JWT_ISSUER
              valueFrom:
                secretKeyRef:
                  name: community-service-secret
                  key: SECRET_ISSUER
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: community-service-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: community-service-secret
                  key: DB_NAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: community-service-secret
                  key: DB_PASSWORD
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: community-service-secret
                  key: DB_USER
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: community-service-secret
                  key: DB_PORT
            - name: PROFILE_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: community-service-secret
                  key: PROFILE_SERVICE_URL
            - name: NOTIFICATION_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: community-service-secret
                  key: NOTIFICATION_SERVICE_URL
            - name: USER_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: community-service-secret
                  key: USER_SERVICE_URL
            - name: OPEN_AI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: community-service-secret
                  key: OPEN_AI_API_KEY
            - name: APP_PORT
              valueFrom:
                secretKeyRef:
                  name: community-service-secret
                  key: APP_PORT
          resources:
            requests:
              memory: "256Mi"
              cpu: "512m"
            limits:
              memory: "512Mi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: community-cluster-ip-service
spec:
  selector:
    app: community-service
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089
  type: ClusterIP